In [1]:
!pip install numpy

In [16]:
import numpy as np

In [3]:
marks=[10 , 20 , 30]

I want marks=[20 , 40 , 60]

In [4]:
marks * 2

[10, 20, 30, 10, 20, 30]

But we are not getting the desired output

```

Here I want marks=[12 , 22 , 32]

In [5]:
marks + [2]

[10, 20, 30, 2]

But we are not getting what we want.we can do it in python easily bu list comphersion.

Let's see how numpy resolved above problem

In [7]:
type(marks)

list

In [6]:
#Create a numpy object
arr=np.array(marks)
arr

array([10, 20, 30])

np.array convert the python list into numpy array

In [8]:
type(arr)

numpy.ndarray

Let's do operation

In [10]:
arr * 2

array([20, 40, 60])

In [14]:
arr + 2

array([12, 22, 32])

How to create numpy arrays ?
One way is  discussed above and next popular one is discussed below

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(10 , 20 , 2)   #Increment of 2

array([10, 12, 14, 16, 18])

In [19]:
np.arange(10 , 20 , 1.5)   #Increment of 1.5

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

Observation : When I set np.arange(10 , 20 , 2)  at 2 all the numbers were Integer.But when I set 1.5 all the number converted into float.
Even one number is float , All the number should be of same datatype.

```

np.linespace tells how many number want to generate between start to end point.
start and end point is included.

In [30]:
print(np.linspace(1 , 10 , 1))
print(np.linspace(1 , 10 , 2))
print(np.linspace(1 , 10 , 3))
print(np.linspace(1 , 10 , 4))
print(np.linspace(1 , 10 , 5))
print(np.linspace(1 , 10 , 10))

[1.]
[ 1. 10.]
[ 1.   5.5 10. ]
[ 1.  4.  7. 10.]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [31]:
lst=list(range(0,10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
[i**2 for i in lst]  #This will give square of every element

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Now Let's do in Numpy

In [36]:
arr=np.array(list(range(0,10)))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

---------------OR-----------

In [39]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

Now lets check time take by above code

In [40]:
%timeit [i**2 for i in lst]

2.53 µs ± 95.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [41]:
%timeit arr*arr

389 ns ± 32.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [43]:
arr=np.arange(10 , 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Now I want 13, 14, 15, 16, 17 from above array.


In [44]:
arr[3:7]

array([13, 14, 15, 16])

Here we are getting till 16. We want till 17.

In [45]:
arr[3:8]

array([13, 14, 15, 16, 17])

In [47]:
np.array([10 , 20 , 30  , 40.0])

array([10., 20., 30., 40.])

In [50]:
np.array([10 , 20 , 30  , 40.0] , int)

array([10, 20, 30, 40])

In [51]:
np.array([10 , 20 , 30  , 40.59] , int)

array([10, 20, 30, 40])

In [54]:
np.array([10 , 20 , 30  , 40.7] , float)

array([10. , 20. , 30. , 40.7])

In [57]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
#Change index number 1 with 110 of arr
arr[1]=110

In [59]:
print(arr)

[ 10 110  12  13  14  15  16  17  18  19  20  21  22  23  24]


In [60]:
arr

array([ 10, 110,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24])

Whatever we did in above in 1D Array. Now let's understand 2D array

In [61]:
lst2d=[[4 , 5 , 6] , [7 , 8 , 9]]
lst2d

[[4, 5, 6], [7, 8, 9]]

Now convert into numpy array.We can convert to numpy array using np.array

In [63]:
arr2d=np.array(lst2d)
arr2d

array([[4, 5, 6],
       [7, 8, 9]])

array([[4, 5, 6],
       [7, 8, 9]])
This is also called matrix . 2D array called as matrix and 1D array called as vector. 

In [64]:
arr2d*2


array([[ 8, 10, 12],
       [14, 16, 18]])

In [65]:
arr2d+2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
arr2d

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d.size #It will gives length of non zero element

6

In [73]:
type(arr2d)

numpy.ndarray

In [72]:
arr2d.shape

(2, 3)

(2, 3) is tupple. (Row , Column).
shape give number of row and number of column in 2D matrix.Not in 3D or 4D matrix


How Can we check dimesnion of array?

In [75]:
arr2d.ndim
#We get 2 .That measn number of dimension is 2.

2

How do we access 8 from arr2d?


In [76]:
arr2d[1][1]

8

The shortest syntax is 

In [77]:
arr2d[1 , 1]

8